name: static
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3

      - name: Compile SCSS
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: scss/main.scss
          destination: static/main.css

      - name: Add and Commit changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add static/*
          git commit -m 'Compiled updated SCSS files'
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      